### ISSUE TITLE
Add icon CoinCollect (CC)

### ISSUE THREAD

**Issue by brrrrrr** [atomiclabs/cryptocurrency-icons#212] opened 2018-09-17 09:37 UTC
Currency name: CoinCollect
Symbol: CC
Website: https://coincollect.cc
Theme color: #ff9500
Logo (SVG): https://en.bitcoin.it/wiki/Promotional_graphics

[cc-logo_1.svg.zip](https://github.com/atomiclabs/cryptocurrency-icons/files/2388000/cc-logo_1.svg.zip)

**Comment by sindresorhus** [comment] 2018-09-17 09:39
Duplicate of #203

**Closed by sindresorhus** 2018-09-17 09:39 UTC
